name: circle_avatar
description: Flutter package for circle avatar widget

homepage: https://your-package-homepage.com
repository: https://link-to-your-repository.com
email: v.perveev3456@gmail.com

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

